### ISSUE TITLE
Unable to install on W10 with Node 7.5

### ISSUE THREAD

**Issue by cmatskas** [lostintangent/az-login#12] opened 2017-06-12 21:23 UTC
Hi, I work with @bradygaster from time to time and I was directed to this repo to try it out. I've tried to install the tooling based on the pre-reqs and the steps you've highlighted but I'm getting the following error when I run: `npm i az-login`

```
c:\Projects\test\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [c:\Projects\tes
t\node_modules\keytar\build\keytar.vcxproj]
```
I have the latest tooling with Node at 7.5 and npm at 4.1.2 on a W10 machine. I'm not sure why it's looking for Windows SDK 8.1. Also, the `keytar` package was nowhere to be found in the node_modules directory so no way to manually pin the W SDK version

**Comment by fiveisprime** [comment] 2017-06-12 21:49
It looks like you have Visual Studio 2015 installed already. Do you recall whether you included 'Visual C++' support in Visual Studio 2015 when installing? I believe it defaults to exclude. :(

You may need to **modify your installation** to include C++ or try running [this C++ installer](http://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe).

**Comment by lostintangent** [comment] 2017-06-12 22:10
As @fiveisprime mentioned, this is a Windows C++ compiler issue, and would affect you installing any NPM module that included native code.

Did you already try running `npm i -g windows-build-tools` from an elevated command prompt? That will ensure you have everything needed to build native NPM modules on Windows.

**Comment by cmatskas** [comment] 2017-06-12 22:13
Yes, I followed the instructions in the pre-reds. Do you reckon I need to restart to resolve the problem?

**Comment by fiveisprime** [comment] 2017-06-12 22:19
This isn't something I'd expect a restart to correct. Did you verify the Visual Studio version and tools that you have installed? There are some potential issues, but I need a better idea of your environment before I can give you some solid direction. :)

If you already had VS installed, pieces of the `windows-build-tools` package will fail silently; if that fails and you did not install C++ support when you installed VS 2015, you'll see this error.

**Comment by cmatskas** [comment] 2017-06-12 23:19
Valid point! I may as well switch to my Mac or Linux and leave my W10 machine as is (i.e. Broken). I'll try in the Mac and let you know but I believe you're right! I never installed the c++ components for VS2015

**Comment by fiveisprime** [comment] 2017-06-13 00:23
There used to be a easy way to get this installed without uninstalling/reinstalling/modifying/weeping: create a new project in VS and choose C++ project type. VS is smart enough to know that it needs to install the components so it will automatically modify itself.

I haven't tried that trick in many years so the advice comes as-is D:

**Comment by bradygaster** [comment] 2017-06-13 12:35
@fiveisprime "weeping." hilarious. you never cease to crack me up buddy.

**Comment by lostintangent** [comment] 2017-07-10 03:16
@cmatskas Any updates on this? Are you still having this issue? As discussed, the problem is related to a native Node dependency, but I'd still love to know if I can make the readme clearer. Thanks!

**Comment by lostintangent** [comment] 2017-07-29 22:38
Closing this per #14, which removes the native module dependency directly from this module.

**Closed by lostintangent** 2017-07-29 22:38 UTC
